#!/usr/bin/env bash
# Displays infinity and beyond
#+ a sleep 2 in between each iteration
# dissplays "im invincible" in between each iteration

while true
do
  echo "To infinity and beyond"
  slepp 2
  trap 'echo "I am invincible!!!"' SIGTERM
done
